version: '3.9'

services:
  redis:
    container_name: redis
    image: 'redis:7.0.7-alpine'
    ports:
      - "6379:6379"
    networks:
      - network
    volumes:
      - cache:/data

networks:
  network:
    driver: bridge

volumes:
  cache:
    driver: local
