export const Errors = {
  TaskNotFound: 'task-not-found',
  TaskInProvidedStatusCantBeDeleted: 'task-in-provided-status-cant-be-deleted',
  TaskMustBeInInitiatedStatus: 'task-must-be-initiated',
  TaskMustBeInTodoStatus: 'task-must-be-in-todo-status',
  TaskTemplateNotFound: 'task-template-not-found',
  SectionNotFound: 'section-not-found',
  SectionNameUnique: 'section-with-provided-name-already-exist',
  SectionIconNameUnique: 'section-with-provided-icon-name-already-exist',
  SectionAlreadyPlanned: 'section-already-planned-for-provided-date',
  SectionAlreadyNotPlanned: 'section-already-not-planned-for-provided-date',
  StoreNameUnique: 'store-with-provided-name-already-exist',
  StoreDeactivated: 'store-is-deactivated',
  UserNotFound: 'user-not-found',
  UserNotAcceptableRole: 'user-not-acceptable-role',
  UserPasswordIncorrect: 'user-password-incorrect',
  UserManagerUsernameUnique: 'user-manager-username-unique',
  UserHQUsernameUnique: 'user-hq-username-unique',
};
